Repository GreenComfyTea/MHWs-YURI-Overlay, pull requests merged in 2025-05, with the labels that each got.

#42 chore(main): release 1.5.0
  CHANGELOG.md
Labels: autorelease: pending, size/S

#45 Update zh-Hans.json
  reframework/data/YURI_Overlay/localizations/zh-Hans.json
Labels: size/M

#46 chore(main): release 1.5.1
  CHANGELOG.md
Labels: autorelease: pending, size/S

#47 chore(main): release 1.5.2
  CHANGELOG.md
Labels: autorelease: pending, size/XS
